FROM centos:latest

#RUN sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

# RUN cd /tmp && curl -fsSL 'https://codeload.github.com/mysql-inception/inception/zip/master' -o 'inception.zip'

#RUN resize -s 80 160

EXPOSE 8511 8511

CMD ["sh", "-c", "while true;do echo hello docker;sleep 1;done;"]
